/**
 * This factory function will take care of the player's play.
 * Currently only need to support computer's play as the player's play will be handle by "eventhandlers.js" REMOVE???
 * @param {string} input_name currently not used
 * @param {gameboard object} enemy_board
 * @param {gameboard object} enemy_div
 */
const Player = (input_name, enemy_board, enemy_div) => {
  const name = input_name;
  const enemyBoard = enemy_board;
  const enemyDiv = enemy_div;

  const playerPlay = e => {
    // Player takes turn
  };

  // Function to run the computer's play
  // Returns true if computer play DID NOT end the game
  // Returns false if computer play hit the last part of the last ship and sunken all ships
  const computerPlay = () => {
    // Computer takes turn
    let index = 0;

    // These x/y coordinates has been sanitized and checked for validity
    [x_coor, y_coor] = getRandCoord();
    enemyBoard.receiveAttack(x_coor, y_coor);

    // Going through all nodes and looking for the dataset coordinatesX/Y to match with the random coordinates generated by getRandCoord()
    enemyDiv.childNodes.forEach(node => {
      if (
        node.dataset.coordinateX == x_coor &&
        node.dataset.coordinateY == y_coor
      ) {
        // Once found and the object is a ship, mark hit as red
        if (typeof enemyBoard.getShipBoard()[x_coor][y_coor] === 'object') {
          enemyDiv.childNodes[index].style.backgroundColor = 'red';
        } // Else, mark the hit as miss with white
        else enemyDiv.childNodes[index].style.backgroundColor = 'white';
      }
      index++;
    });

    // Checking if computerPlay has successfully sunken all ships
    if (enemyBoard.sunkenAll()) {
      // If sunk all ships, mark message on status board with "lost" message
      let status_board = document.querySelector('.ship-div');
      status_board.firstChild.innerHTML =
        'All of your ships has been sunk. You lost!';
      // REMOVE this once generated sunken ships on enemy board
      status_board.removeChild(status_board.lastChild);
      return false;
    }
    return true;
  };

  // Private function
  const getRandCoord = () => {
    x_play = Math.floor(Math.random() * 10);
    y_play = Math.floor(Math.random() * 10);
    // Check to make sure coordinates had not been marked
    while (enemyBoard.checkAttack(x_play, y_play)) {
      // Try again with new coordinates
      x_play = Math.floor(Math.random() * 10);
      y_play = Math.floor(Math.random() * 10);
    }
    return [x_play, y_play];
  };

  return { playerPlay, computerPlay };
};

module.exports = Player;
